PREFIX dt: <https://w3id.org/rdf-tensor/datatypes#>
PREFIX dtf: <https://w3id.org/rdf-tensor/functions#>
PREFIX ocs_papers: <https://w3id.org/ocs/ont/papers/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX fabio: <http://purl.org/spar/fabio/>
PREFIX fn: <http://www.w3.org/2005/xpath-functions#>

SELECT ?title1 ?title2 (fn:round(?similarity, 3) AS ?cosineSimilarity)
WHERE {
    ?s1 a fabio:ResearchPaper ;
        ocs_papers:hasWordEmbedding ?o1 ;
        dcterms:title ?title1 .

    ?s2 a fabio:ResearchPaper ;
        ocs_papers:hasWordEmbedding ?o2 ;
        dcterms:title ?title2 .

    BIND(dtf:cosineSimilarity(?o1, ?o2) AS ?similarity)
    FILTER (STR(?s1) < STR(?s2))
}
ORDER BY DESC(?similarity)
LIMIT 5