PREFIX dt: <https://w3id.org/rdf-tensor/datatypes#>
PREFIX dtf: <https://w3id.org/rdf-tensor/functions#>
PREFIX dta: <https://w3id.org/rdf-tensor/aggregators#>
PREFIX ocs_papers: <https://w3id.org/ocs/ont/papers/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX fabio: <http://purl.org/spar/fabio/>
PREFIX schema: <http://schema.org/>
PREFIX fn: <http://www.w3.org/2005/xpath-functions#>
PREFIX frbr: <http://purl.org/vocab/frbr/core#>

SELECT ?title (fn:round(?norm2, 5) AS ?result)
WHERE {
    ?paper a fabio:ResearchPaper ;
        ocs_papers:hasWordEmbedding ?o ;
        frbr:realization ?realization ;
        dcterms:title ?title .

    ?realization a fabio:JournalArticle .

    BIND(dtf:getSubDT(?o, "{\"type\":\"int32\",\"shape\":[4],\"data\":[0, 1, 2, 3]}"^^dt:NumericDataTensor) AS ?subDT)
    BIND(dtf:norm2(-1, ?subDT) AS ?norm2)
}
ORDER BY DESC(?norm2)
LIMIT 5